
-- ============================================================


-- ============================================================

-- ============================================================
-- TABLE DEFINITIONS
-- ============================================================

-- DEPARTMENTS table
CREATE TABLE departments (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL UNIQUE
);

-- USERS table
CREATE TABLE users (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR2(255) NOT NULL,
    email               VARCHAR2(255) NOT NULL UNIQUE,
    password            VARCHAR2(255) NOT NULL,
    employee_id         VARCHAR2(255) UNIQUE,
    role                VARCHAR2(20) NOT NULL,
    department          VARCHAR2(255),
    designation         VARCHAR2(255),
    manager_id          NUMBER,
    phone               VARCHAR2(20),
    address             VARCHAR2(500),
    emergency_contact   VARCHAR2(255),
    joining_date        DATE,
    active              NUMBER(1) DEFAULT 1 NOT NULL,
    salary              NUMBER(15,2),
    CONSTRAINT fk_user_manager FOREIGN KEY (manager_id) REFERENCES users(id)
);

-- LEAVE_TYPES table
CREATE TABLE leave_types (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255) NOT NULL UNIQUE,
    default_days    NUMBER NOT NULL
);

-- LEAVE_REQUESTS table
CREATE TABLE leave_requests (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    leave_type          VARCHAR2(255) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE NOT NULL,
    reason              VARCHAR2(500),
    status              VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    manager_comment     VARCHAR2(500),
    applied_date        DATE,
    CONSTRAINT fk_leave_employee FOREIGN KEY (employee_id) REFERENCES users(id)
);

-- LEAVE_BALANCES table
CREATE TABLE leave_balances (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     NUMBER NOT NULL,
    leave_type      VARCHAR2(255) NOT NULL,
    total_days      NUMBER NOT NULL,
    used_days       NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT fk_balance_employee FOREIGN KEY (employee_id) REFERENCES users(id),
    CONSTRAINT unq_leave_balance UNIQUE (employee_id, leave_type)
);

-- GOALS table
CREATE TABLE goals (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    description         VARCHAR2(1000) NOT NULL,
    deadline            DATE,
    priority            VARCHAR2(20) DEFAULT 'MEDIUM',
    progress            NUMBER DEFAULT 0 NOT NULL,
    manager_comment     VARCHAR2(1000),
    CONSTRAINT fk_goal_employee FOREIGN KEY (employee_id) REFERENCES users(id)
);

-- PERFORMANCE_REVIEWS table
CREATE TABLE performance_reviews (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id         NUMBER NOT NULL,
    deliverables        VARCHAR2(2000),
    accomplishments     VARCHAR2(2000),
    improvements        VARCHAR2(2000),
    self_rating         NUMBER,
    manager_rating      NUMBER,
    manager_feedback    VARCHAR2(2000),
    status              VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    review_year         NUMBER,
    CONSTRAINT fk_review_employee FOREIGN KEY (employee_id) REFERENCES users(id)
);

-- ANNOUNCEMENTS table
CREATE TABLE announcements (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR2(255) NOT NULL,
    description     VARCHAR2(2000),
    created_date    DATE DEFAULT SYSDATE
);

-- NOTIFICATIONS table
CREATE TABLE notifications (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    message         VARCHAR2(500) NOT NULL,
    is_read         NUMBER(1) DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- HOLIDAYS table
CREATE TABLE holidays (
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(255) NOT NULL,
    holiday_date    DATE NOT NULL
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_manager ON users(manager_id);
CREATE INDEX idx_users_department ON users(department);
CREATE INDEX idx_users_active ON users(active);
CREATE INDEX idx_leave_req_emp ON leave_requests(employee_id);
CREATE INDEX idx_leave_req_status ON leave_requests(status);
CREATE INDEX idx_leave_bal_emp ON leave_balances(employee_id);
CREATE INDEX idx_goals_emp ON goals(employee_id);
CREATE INDEX idx_reviews_emp ON performance_reviews(employee_id);
CREATE INDEX idx_reviews_status ON performance_reviews(status);
CREATE INDEX idx_notif_user ON notifications(user_id);
CREATE INDEX idx_notif_read ON notifications(is_read);

-- ============================================================
-- PL/SQL STORED PROCEDURES & FUNCTIONS
-- ============================================================

-- ---- USER PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_register_user(
    p_name IN VARCHAR2,
    p_email IN VARCHAR2,
    p_password IN VARCHAR2,
    p_employee_id IN VARCHAR2,
    p_role IN VARCHAR2,
    p_department IN VARCHAR2,
    p_designation IN VARCHAR2,
    p_manager_id IN NUMBER,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2,
    p_emergency_contact IN VARCHAR2,
    p_joining_date IN DATE,
    p_salary IN NUMBER,
    p_user_id OUT NUMBER
) AS
BEGIN
    INSERT INTO users (name, email, password, employee_id, role, department, designation,
                       manager_id, phone, address, emergency_contact, joining_date, active, salary)
    VALUES (p_name, p_email, p_password, p_employee_id, p_role, p_department, p_designation,
            p_manager_id, p_phone, p_address, p_emergency_contact, p_joining_date, 1, p_salary)
    RETURNING id INTO p_user_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_user(
    p_id IN NUMBER,
    p_name IN VARCHAR2,
    p_department IN VARCHAR2,
    p_designation IN VARCHAR2,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2,
    p_emergency_contact IN VARCHAR2,
    p_manager_id IN NUMBER,
    p_role IN VARCHAR2,
    p_salary IN NUMBER
) AS
BEGIN
    UPDATE users SET
        name = NVL(p_name, name),
        department = NVL(p_department, department),
        designation = NVL(p_designation, designation),
        phone = NVL(p_phone, phone),
        address = NVL(p_address, address),
        emergency_contact = NVL(p_emergency_contact, emergency_contact),
        manager_id = p_manager_id,
        role = NVL(p_role, role),
        salary = NVL(p_salary, salary)
    WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_profile(
    p_id IN NUMBER,
    p_phone IN VARCHAR2,
    p_address IN VARCHAR2,
    p_emergency_contact IN VARCHAR2
) AS
BEGIN
    UPDATE users SET
        phone = NVL(p_phone, phone),
        address = NVL(p_address, address),
        emergency_contact = NVL(p_emergency_contact, emergency_contact)
    WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_deactivate_user(p_id IN NUMBER) AS
BEGIN
    UPDATE users SET active = 0 WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_reactivate_user(p_id IN NUMBER) AS
BEGIN
    UPDATE users SET active = 1 WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_assign_manager(p_employee_id IN NUMBER, p_manager_id IN NUMBER) AS
BEGIN
    UPDATE users SET manager_id = p_manager_id WHERE id = p_employee_id;
    COMMIT;
END;
/

-- ---- LEAVE PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_apply_leave(
    p_employee_id IN NUMBER,
    p_leave_type IN VARCHAR2,
    p_start_date IN DATE,
    p_end_date IN DATE,
    p_reason IN VARCHAR2,
    p_leave_id OUT NUMBER
) AS
    v_days NUMBER;
BEGIN
    v_days := p_end_date - p_start_date + 1;

    INSERT INTO leave_requests (employee_id, leave_type, start_date, end_date, reason, status, applied_date)
    VALUES (p_employee_id, p_leave_type, p_start_date, p_end_date, p_reason, 'PENDING', SYSDATE)
    RETURNING id INTO p_leave_id;

    -- Deduct leave balance
    UPDATE leave_balances SET used_days = used_days + v_days
    WHERE employee_id = p_employee_id AND UPPER(TRIM(leave_type)) = UPPER(TRIM(p_leave_type));

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_cancel_leave(p_leave_id IN NUMBER) AS
    v_emp_id NUMBER;
    v_leave_type VARCHAR2(255);
    v_start DATE;
    v_end DATE;
    v_days NUMBER;
BEGIN
    -- Get employee, leave type and days
    SELECT employee_id, leave_type, start_date, end_date INTO v_emp_id, v_leave_type, v_start, v_end
    FROM leave_requests WHERE id = p_leave_id;
    
    v_days := v_end - v_start + 1;

    UPDATE leave_requests SET status = 'CANCELLED' WHERE id = p_leave_id AND status = 'PENDING';

    -- Rollback leave balance
    UPDATE leave_balances SET used_days = used_days - v_days
    WHERE employee_id = v_emp_id AND UPPER(TRIM(leave_type)) = UPPER(TRIM(v_leave_type));

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_approve_leave(
    p_leave_id IN NUMBER,
    p_comment IN VARCHAR2,
    p_days IN NUMBER
) AS
BEGIN
    -- Update leave status (balance already deducted on apply)
    UPDATE leave_requests SET status = 'APPROVED', manager_comment = p_comment
    WHERE id = p_leave_id AND status = 'PENDING';

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_reject_leave(
    p_leave_id IN NUMBER,
    p_comment IN VARCHAR2
) AS
    v_emp_id NUMBER;
    v_leave_type VARCHAR2(255);
    v_start DATE;
    v_end DATE;
    v_days NUMBER;
BEGIN
    -- Get employee, leave type and days
    SELECT employee_id, leave_type, start_date, end_date INTO v_emp_id, v_leave_type, v_start, v_end
    FROM leave_requests WHERE id = p_leave_id;
    
    v_days := v_end - v_start + 1;

    UPDATE leave_requests SET status = 'REJECTED', manager_comment = p_comment
    WHERE id = p_leave_id AND status = 'PENDING';

    -- Rollback leave balance
    UPDATE leave_balances SET used_days = used_days - v_days
    WHERE employee_id = v_emp_id AND UPPER(TRIM(leave_type)) = UPPER(TRIM(v_leave_type));

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_adjust_leave_balance(
    p_employee_id IN NUMBER,
    p_leave_type IN VARCHAR2,
    p_total_days IN NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM leave_balances
    WHERE employee_id = p_employee_id AND UPPER(TRIM(leave_type)) = UPPER(TRIM(p_leave_type));

    IF v_count > 0 THEN
        UPDATE leave_balances SET total_days = p_total_days
        WHERE employee_id = p_employee_id AND UPPER(TRIM(leave_type)) = UPPER(TRIM(p_leave_type));
    ELSE
        INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days)
        VALUES (p_employee_id, p_leave_type, p_total_days, 0);
    END IF;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_init_leave_balance(
    p_employee_id IN NUMBER,
    p_leave_type IN VARCHAR2,
    p_total_days IN NUMBER
) AS
BEGIN
    INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days)
    VALUES (p_employee_id, p_leave_type, p_total_days, 0);
    COMMIT;
END;
/

-- ---- LEAVE TYPE PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_add_leave_type(
    p_name IN VARCHAR2,
    p_default_days IN NUMBER,
    p_id OUT NUMBER
) AS
BEGIN
    INSERT INTO leave_types (name, default_days) VALUES (p_name, p_default_days)
    RETURNING id INTO p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_leave_type(
    p_id IN NUMBER,
    p_name IN VARCHAR2,
    p_default_days IN NUMBER
) AS
BEGIN
    UPDATE leave_types SET name = p_name, default_days = p_default_days WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_delete_leave_type(p_id IN NUMBER) AS
BEGIN
    DELETE FROM leave_types WHERE id = p_id;
    COMMIT;
END;
/

-- ---- GOAL PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_create_goal(
    p_employee_id IN NUMBER,
    p_description IN VARCHAR2,
    p_deadline IN DATE,
    p_priority IN VARCHAR2,
    p_goal_id OUT NUMBER
) AS
BEGIN
    INSERT INTO goals (employee_id, description, deadline, priority, progress)
    VALUES (p_employee_id, p_description, p_deadline, NVL(p_priority, 'MEDIUM'), 0)
    RETURNING id INTO p_goal_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_goal_progress(
    p_goal_id IN NUMBER,
    p_progress IN NUMBER
) AS
BEGIN
    UPDATE goals SET progress = p_progress WHERE id = p_goal_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_add_goal_comment(
    p_goal_id IN NUMBER,
    p_comment IN VARCHAR2
) AS
BEGIN
    UPDATE goals SET manager_comment = p_comment WHERE id = p_goal_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_delete_goal(p_goal_id IN NUMBER) AS
BEGIN
    DELETE FROM goals WHERE id = p_goal_id;
    COMMIT;
END;
/

-- ---- PERFORMANCE REVIEW PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_create_review(
    p_employee_id IN NUMBER,
    p_deliverables IN VARCHAR2,
    p_accomplishments IN VARCHAR2,
    p_improvements IN VARCHAR2,
    p_self_rating IN NUMBER,
    p_review_year IN NUMBER,
    p_review_id OUT NUMBER
) AS
BEGIN
    INSERT INTO performance_reviews (employee_id, deliverables, accomplishments, improvements,
                                     self_rating, status, review_year)
    VALUES (p_employee_id, p_deliverables, p_accomplishments, p_improvements,
            p_self_rating, 'DRAFT', p_review_year)
    RETURNING id INTO p_review_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_submit_review(p_review_id IN NUMBER) AS
BEGIN
    UPDATE performance_reviews SET status = 'SUBMITTED' WHERE id = p_review_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_provide_feedback(
    p_review_id IN NUMBER,
    p_manager_rating IN NUMBER,
    p_manager_feedback IN VARCHAR2
) AS
BEGIN
    UPDATE performance_reviews SET
        manager_rating = p_manager_rating,
        manager_feedback = p_manager_feedback,
        status = 'REVIEWED'
    WHERE id = p_review_id;
    COMMIT;
END;
/

-- ---- DEPARTMENT PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_add_department(
    p_name IN VARCHAR2,
    p_id OUT NUMBER
) AS
BEGIN
    INSERT INTO departments (name) VALUES (p_name) RETURNING id INTO p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_department(
    p_id IN NUMBER,
    p_name IN VARCHAR2
) AS
BEGIN
    UPDATE departments SET name = p_name WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_delete_department(p_id IN NUMBER) AS
BEGIN
    DELETE FROM departments WHERE id = p_id;
    COMMIT;
END;
/

-- ---- ANNOUNCEMENT PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_add_announcement(
    p_title IN VARCHAR2,
    p_description IN VARCHAR2,
    p_id OUT NUMBER
) AS
BEGIN
    INSERT INTO announcements (title, description, created_date)
    VALUES (p_title, p_description, SYSDATE)
    RETURNING id INTO p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_update_announcement(
    p_id IN NUMBER,
    p_title IN VARCHAR2,
    p_description IN VARCHAR2
) AS
BEGIN
    UPDATE announcements SET title = p_title, description = p_description WHERE id = p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_delete_announcement(p_id IN NUMBER) AS
BEGIN
    DELETE FROM announcements WHERE id = p_id;
    COMMIT;
END;
/

-- ---- NOTIFICATION PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_create_notification(
    p_user_id IN NUMBER,
    p_message IN VARCHAR2,
    p_notif_id OUT NUMBER
) AS
BEGIN
    INSERT INTO notifications (user_id, message, is_read, created_at)
    VALUES (p_user_id, p_message, 0, SYSTIMESTAMP)
    RETURNING id INTO p_notif_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_mark_notification_read(p_notif_id IN NUMBER) AS
BEGIN
    UPDATE notifications SET is_read = 1 WHERE id = p_notif_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_mark_all_notifications_read(p_user_id IN NUMBER) AS
BEGIN
    UPDATE notifications SET is_read = 1 WHERE user_id = p_user_id;
    COMMIT;
END;
/

-- ---- HOLIDAY PROCEDURES ----

CREATE OR REPLACE PROCEDURE sp_add_holiday(
    p_name IN VARCHAR2,
    p_date IN DATE,
    p_id OUT NUMBER
) AS
BEGIN
    INSERT INTO holidays (name, holiday_date) VALUES (p_name, p_date)
    RETURNING id INTO p_id;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE sp_delete_holiday(p_id IN NUMBER) AS
BEGIN
    DELETE FROM holidays WHERE id = p_id;
    COMMIT;
END;
/


-- ============================================================
-- SEED DATA
-- ============================================================

-- Departments
INSERT INTO departments (name) VALUES ('Engineering');
INSERT INTO departments (name) VALUES ('Human Resources');
INSERT INTO departments (name) VALUES ('Finance');
INSERT INTO departments (name) VALUES ('Marketing');
INSERT INTO departments (name) VALUES ('Operations');

-- Leave Types
INSERT INTO leave_types (name, default_days) VALUES ('Casual Leave', 12);
INSERT INTO leave_types (name, default_days) VALUES ('Sick Leave', 10);
INSERT INTO leave_types (name, default_days) VALUES ('Paid Leave', 15);

-- Admin User (password: admin123 - BCrypt encoded)
INSERT INTO users (name, email, password, employee_id, role, department, designation, phone, joining_date, active)
VALUES ('Admin User', 'admin@revworkforce.com',
        '$2a$10$QSnHurm1WVhUwKgagbH9m.FurStndJ3dbb4WZGRVBVw1l/0KM4jZC',
        'EMP00001', 'ADMIN', 'Human Resources', 'System Administrator', '9876543210',
        TO_DATE('2023-01-01', 'YYYY-MM-DD'), 1);

-- Manager User (password: manager123 - BCrypt encoded)
INSERT INTO users (name, email, password, employee_id, role, department, designation, phone, manager_id, joining_date, active, salary)
VALUES ('Rahul Sharma', 'manager@revworkforce.com',
        '$2a$10$Gm9DsKCFXtVlOZLA0IUM2uJCYsYJOp2H7ePdv27KaNzUlvcveD2ay',
        'EMP00002', 'MANAGER', 'Engineering', 'Engineering Manager', '9876543211',
        1, TO_DATE('2023-03-15', 'YYYY-MM-DD'), 1, 120000);

-- Employee Users (password: employee123 - BCrypt encoded)
INSERT INTO users (name, email, password, employee_id, role, department, designation, phone, manager_id, joining_date, active, salary)
VALUES ('Priya Patel', 'employee@revworkforce.com',
        '$2a$10$ozcV4fgBLXmBpQFNbrjfP.XIsZb5dL7obGUeNAXaxAsiOEDj9zk3q',
        'EMP00003', 'EMPLOYEE', 'Engineering', 'Software Engineer', '9876543212',
        2, TO_DATE('2023-06-01', 'YYYY-MM-DD'), 1, 80000);

INSERT INTO users (name, email, password, employee_id, role, department, designation, phone, manager_id, joining_date, active, salary)
VALUES ('Amit Kumar', 'amit@revworkforce.com',
        '$2a$10$ozcV4fgBLXmBpQFNbrjfP.XIsZb5dL7obGUeNAXaxAsiOEDj9zk3q',
        'EMP00004', 'EMPLOYEE', 'Engineering', 'Senior Developer', '9876543213',
        2, TO_DATE('2023-04-10', 'YYYY-MM-DD'), 1, 95000);

INSERT INTO users (name, email, password, employee_id, role, department, designation, phone, manager_id, joining_date, active, salary)
VALUES ('Sneha Gupta', 'sneha@revworkforce.com',
        '$2a$10$ozcV4fgBLXmBpQFNbrjfP.XIsZb5dL7obGUeNAXaxAsiOEDj9zk3q',
        'EMP00005', 'EMPLOYEE', 'Finance', 'Accountant', '9876543214',
        1, TO_DATE('2023-07-20', 'YYYY-MM-DD'), 1, 70000);

-- Leave Balances for all users
-- Admin
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (1, 'Casual Leave', 12, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (1, 'Sick Leave', 10, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (1, 'Paid Leave', 15, 0);
-- Manager
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (2, 'Casual Leave', 12, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (2, 'Sick Leave', 10, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (2, 'Paid Leave', 15, 0);
-- Employee 1
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (3, 'Casual Leave', 12, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (3, 'Sick Leave', 10, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (3, 'Paid Leave', 15, 0);
-- Employee 2
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (4, 'Casual Leave', 12, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (4, 'Sick Leave', 10, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (4, 'Paid Leave', 15, 0);
-- Employee 3
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (5, 'Casual Leave', 12, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (5, 'Sick Leave', 10, 0);
INSERT INTO leave_balances (employee_id, leave_type, total_days, used_days) VALUES (5, 'Paid Leave', 15, 0);

-- Holidays
INSERT INTO holidays (name, holiday_date) VALUES ('Republic Day', TO_DATE('2026-01-26', 'YYYY-MM-DD'));
INSERT INTO holidays (name, holiday_date) VALUES ('Holi', TO_DATE('2026-03-14', 'YYYY-MM-DD'));
INSERT INTO holidays (name, holiday_date) VALUES ('Independence Day', TO_DATE('2026-08-15', 'YYYY-MM-DD'));
INSERT INTO holidays (name, holiday_date) VALUES ('Gandhi Jayanti', TO_DATE('2026-10-02', 'YYYY-MM-DD'));
INSERT INTO holidays (name, holiday_date) VALUES ('Diwali', TO_DATE('2026-10-20', 'YYYY-MM-DD'));
INSERT INTO holidays (name, holiday_date) VALUES ('Christmas', TO_DATE('2026-12-25', 'YYYY-MM-DD'));

-- Announcements
INSERT INTO announcements (title, description, created_date)
VALUES ('Welcome to RevWorkForce!',
        'We are excited to launch our new HRM system. All employees can now manage leaves, goals, and performance reviews online.',
        SYSDATE);
INSERT INTO announcements (title, description, created_date)
VALUES ('Annual Performance Review Cycle',
        'The annual performance review cycle for 2026 has begun. Please submit your self-assessments by March 31st.',
        SYSDATE);

COMMIT;

-- ============================================================
-- VERIFICATION QUERIES (run these to check if setup worked)
-- ============================================================
-- SELECT * FROM departments;
-- SELECT id, name, email, role, department FROM users;
-- SELECT * FROM leave_types;
-- SELECT * FROM leave_balances;
-- SELECT * FROM holidays;
-- SELECT * FROM announcements;
